# Generated by Django 5.0 on 2025-12-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
